dist: trusty

os:
- linux

language: go

go:
- 1.x
- tip

matrix:
  allow_failures:
  - go: tip

before_install:
- go get github.com/Masterminds/glide
- go get github.com/mattn/goveralls
- go get github.com/alecthomas/gometalinter

install:
- glide install --strip-vendor
- gometalinter --install

script:
- make test
- goveralls -service=travis-ci
