AWSTemplateFormatVersion: "2010-09-09"
Description: "Load Balancer for Kubernetes Ingress"
Parameters:
    LoadBalancerSchemeParameter:
        Type: String
        Description: The Load Balancer scheme - "internal" or "internet-facing"
        Default: "internet-facing"
    LoadBalancerSecurityGroupParameter:
        Type: AWS::EC2::SecurityGroup::Id
        Description: The security group ID for the Load Balancer
    LoadBalancerSubnetsParameter:
        Type: List<AWS::EC2::Subnet::Id>
        Description: The list of subnets IDs for the Load Balancer
    TargetGroupHealthCheckPathParameter:
        Type: String
        Description: The healthcheck path
        Default: /kube-system/healthz
    TargetGroupHealthCheckPortParameter:
        Type: Number
        Description: The healthcheck port
        Default: 9999
    TargetGroupHealthCheckIntervalParameter:
        Type: Number
        Description: The healthcheck interval
        Default: 10
    TargetGroupVPCIDParameter:
        Type: AWS::EC2::VPC::Id
        Description: The VPCID for the TargetGroup
    ListenerCertificatesParameter:
        Type: String
        Description: The HTTPS Listener certificate ARNs (IAM/ACM)
        Default: ""

Conditions:
    CreateHTTPSListener: !Not [ !Equals [ !Ref ListenerCertificatesParameter, "" ] ]

Resources:
    HTTPListener:
        Type : AWS::ElasticLoadBalancingV2::Listener
        Properties:
            DefaultActions:
                - Type: forward
                  TargetGroupArn: !Ref TG
            LoadBalancerArn: !Ref LB
            Port: 80
            Protocol: HTTP

    HTTPSListener:
        Type : AWS::ElasticLoadBalancingV2::Listener
        Condition: CreateHTTPSListener
        Properties:
            DefaultActions:
                - Type: forward
                  TargetGroupArn: !Ref TG
            LoadBalancerArn: !Ref LB
            Port: 443
            Protocol: HTTPS
            Certificates: []

    LB:
        Type: AWS::ElasticLoadBalancingV2::LoadBalancer
        Properties:
            Scheme: !Ref LoadBalancerSchemeParameter
            SecurityGroups:
                - !Ref LoadBalancerSecurityGroupParameter
            Subnets: !Ref LoadBalancerSubnetsParameter
            Tags:
                - Key: StackName
                  Value: !Ref AWS::StackName

    TG:
        Type: AWS::ElasticLoadBalancingV2::TargetGroup
        Properties:
          HealthCheckIntervalSeconds: !Ref TargetGroupHealthCheckIntervalParameter
          HealthCheckPath: !Ref TargetGroupHealthCheckPathParameter
          Port: !Ref TargetGroupHealthCheckPortParameter
          Protocol: HTTP
          VpcId: !Ref TargetGroupVPCIDParameter

Outputs:
    LoadBalancerDNSName:
        Description: DNS name for the LoadBalancer
        Value: !GetAtt LB.DNSName
    TargetGroupARN:
        Description: The ARN of the TargetGroup
        Value: !Ref TG
